### ISSUE TITLE
Performance issues with MobPlugin causes the server Freezes and Player times out

### ISSUE THREAD

**Issue by MrRazamataz** [PowerNukkit/PowerNukkit#301]
Debug Paste : https://hastebin.com/ponamufari
Timings : https://timings.aikar.co/?id=e8a288117327470198b89c0e94d99929

**Comment by joserobjr** [comment]
Can be related to #312

**Comment by joserobjr** [comment]
Can you try with the latest build?
A commit that can fix a potential memory leak has been pushed to the PN-115 branch:
https://github.com/GameModsBR/PowerNukkit/actions

**Comment by MrRazamataz** [comment]
Ok but I also fixed the issue. As with most freezing issues that I have had it has been the MobPlugin (https://nukkitx.com/resources/mobplugin.3/)  which has been freezing it, I have attached what settings I have the MobPlugin set to. 
[config.zip](https://github.com/GameModsBR/PowerNukkit/files/4854150/config.zip)
[config.txt](https://github.com/GameModsBR/PowerNukkit/files/4854151/config.txt)
 
I have attached as both a txt (originally a .yml) and a zip containing the un-txt-ified .yml.

**Comment by good777LUCKY** [comment]
Me too. MobPlugin causing lot of performance problem.

**Comment by joserobjr** [comment]
Freezes and timeouts were probably being caused by #319

**Comment by good777LUCKY** [comment]
> Freezes and timeouts were probably being caused by #319

It is fixed on downgraded Raknet version

**Comment by joserobjr** [comment]
Awesome, thank you for sharing that it worked :D

**Comment by good777LUCKY** [comment]
It was improved but it is very laggy than Nukkit 1.0.

**Comment by good777LUCKY** [comment]
RAM leaking problem was fixed but CPU usage is like 300%. When I remove MobPlugin server will be fine but when I put it again it will be like that. (RAM was fine)

**Comment by Genife173** [comment]
Well, have it been fixed? My server still freezes. Everything is fine without MobPlugin.

**Comment by tuilakhanh** [comment]
@Genife173 update it to lastest version and use my config

https://github.com/PowerNukkit/PowerNukkit/issues/301#issuecomment-661010807

**Comment by Genife173** [comment]
> @Genife173 update it to lastest version and use my config
> 
> https://hastebin.com/epazituyuz.shell

This should fix the server freeze issue?

**Comment by Genife173** [comment]
> @ Genife173 обнови его до последней версии и используй мой конфиг
> 
> https://hastebin.com/epazituyuz.shell

Сервер теперь зависает, потом всех выкидывает, и потом они могут снова зайти. И так каждые 20-30 минут.

**Comment by MrRazamataz** [comment]
> Well, have it been fixed? My server still freezes. Everything is fine without MobPlugin.

Try my settings which I posted previously.

**Comment by Genife173** [comment]
> > Ну, это было исправлено? Мой сервер все еще зависает. Все нормально без MobPlugin.
> 
> Попробуйте мои настройки, которые я опубликовал ранее.

It gives almost nothing. If several players enter the server, lags begin after a while, and then a complete freeze and crash.

**Comment by Genife173** [comment]
> > Ну, это было исправлено? Мой сервер все еще зависает. Все нормально без MobPlugin.
> 
> Попробуйте мои настройки, которые я опубликовал ранее.
-----
The situation got better, but there were 4 players on the server. All players took turns leaving the server with a timeout.

Here is part of the log:
[log.txt](https://github.com/PowerNukkit/PowerNukkit/files/4971677/log.txt)

**Comment by joserobjr** [comment]
I removed the needs testing status because it has been confirmed by the community.

**Comment by good777LUCKY** [comment]
PowerNukkit performance issue was fixed in 1.15.0-dev version of https://github.com/Nukkit-coders/MobPlugin/commit/e98c07421257ea017a1210be9a7e4b7b2453ae43.

**Comment by Genife173** [comment]
> Проблема производительности PowerNukkit была исправлена ​​в версии [Nukkit-coders / MobPlugin @ e98c074](https://github.com/Nukkit-coders/MobPlugin/commit/e98c07421257ea017a1210be9a7e4b7b2453ae43) версии 1.15.0-dev .
--
Спасибо, да, проблемы больше нет.

**Comment by Genife173** [comment]
> Проблема производительности PowerNukkit была исправлена ​​в версии [Nukkit-coders / MobPlugin @ e98c074](https://github.com/Nukkit-coders/MobPlugin/commit/e98c07421257ea017a1210be9a7e4b7b2453ae43) версии 1.15.0-dev .

--

Thank you, yes, the problem is gone.

**Comment by joserobjr** [comment]
Resolved by the plugin developers.
